*** Settings ***
Documentation     Test suite for validating PowerPoint presentations generated by VBA
...               These tests validate the structural integrity of generated timelines
...               without requiring PowerPoint to be installed (uses python-pptx).
Resource          resources/common.robot
Resource          resources/powerpoint_validation.robot
Resource          resources/data_excel.robot
Library           libraries/PowerPointValidator.py
Library           libraries/ExcelValidator.py
Library           OperatingSystem
Suite Setup       Setup PowerPoint Test Suite
Suite Teardown    Cleanup PowerPoint Test Suite

*** Variables ***
${PPTX_FILE_PATH}       %{PPTX_FILE_PATH=data/baseline/expected_timeline.pptx}
${EXCEL_FILE_PATH}      %{EXCEL_FILE_PATH=../timeline.xlsx}
${EXCEL_SHEET_NAME}     %{EXCEL_SHEET_NAME=TimelineData}
${BASELINE_PPTX}        data/baseline/expected_timeline.pptx

*** Test Cases ***
Verify PowerPoint File Exists
    [Documentation]    Verify that the PowerPoint file exists for testing
    [Tags]    smoke    powerpoint    structural
    File Should Exist    ${PPTX_FILE_PATH}    PowerPoint file not found: ${PPTX_FILE_PATH}

Verify Presentation Can Be Loaded
    [Documentation]    Verify that the presentation can be loaded successfully
    [Tags]    smoke    powerpoint    structural
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${summary}=    Get Presentation Summary
    Log    Presentation summary: ${summary}    level=INFO
    Close PowerPoint Presentation

Verify At Least One Slide Created
    [Documentation]    Verify that the timeline generated at least one slide
    [Tags]    powerpoint    structural
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    Verify Slide Created
    Close PowerPoint Presentation

Verify Slide Dimensions Are Correct
    [Documentation]    Verify slide has expected 16:9 dimensions (960x540 points)
    [Tags]    powerpoint    structural
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    Verify Slide Dimensions    960    540
    Close PowerPoint Presentation

Verify Slide Has Shapes
    [Documentation]    Verify that the slide contains timeline shapes
    [Tags]    powerpoint    structural
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    Verify Shape Count    min_shapes=5
    Close PowerPoint Presentation

Verify Timeline Structure
    [Documentation]    Validate the overall timeline structure
    [Tags]    powerpoint    structural
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${results}=    Validate Timeline Structure
    Log    Timeline structure validation: ${results}    level=INFO
    Should Be True    ${results}[valid]    Timeline structure validation failed: ${results}[errors]
    Close PowerPoint Presentation

Verify Swimlane Headers Present
    [Documentation]    Verify that swimlane headers from Excel are present in PowerPoint
    [Tags]    powerpoint    structural    swimlanes
    # Get expected swimlanes from Excel
    ${expected_swimlanes}=    Load Excel And Get Expected Swimlanes    ${EXCEL_FILE_PATH}    ${EXCEL_SHEET_NAME}
    ${swimlane_count}=    Get Length    ${expected_swimlanes}
    Skip If    ${swimlane_count} == 0    No swimlanes defined in Excel data
    
    # Validate in PowerPoint
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${results}=    Validate Swimlanes Present    ${expected_swimlanes}
    Log    Found swimlanes: ${results}[found]    level=INFO
    Log    Missing swimlanes: ${results}[missing]    level=INFO
    Close PowerPoint Presentation

Verify Event Labels Present
    [Documentation]    Verify that event labels from Excel are present in PowerPoint
    [Tags]    powerpoint    structural    events
    # Get expected events from Excel
    ${expected_events}=    Load Excel And Get Expected Events    ${EXCEL_FILE_PATH}    ${EXCEL_SHEET_NAME}
    
    # Validate in PowerPoint
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${results}=    Validate Events Present    ${expected_events}
    Log    Found events: ${results}[found]    level=INFO
    Log    Missing events: ${results}[missing]    level=INFO
    Close PowerPoint Presentation

Verify Milestone Events Present
    [Documentation]    Verify that milestone events are represented on the timeline
    [Tags]    powerpoint    structural    milestones
    # Get milestones from Excel
    ${all_events}=    Load Excel And Get Expected Events    ${EXCEL_FILE_PATH}    ${EXCEL_SHEET_NAME}
    ${milestones}=    Create List
    FOR    ${event}    IN    @{all_events}
        ${type}=    Get From Dictionary    ${event}    Type
        IF    "${type}" in ["Milestone", "milestone"]
            Append To List    ${milestones}    ${event}
        END
    END
    
    ${milestone_count}=    Get Length    ${milestones}
    Skip If    ${milestone_count} == 0    No milestones in Excel data
    
    # Validate milestones in PowerPoint
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    FOR    ${milestone}    IN    @{milestones}
        ${name}=    Get From Dictionary    ${milestone}    Task Name
        ${shapes}=    Find Shapes By Text    ${name}
        ${found}=    Get Length    ${shapes}
        Log    Milestone "${name}": ${found} shapes found    level=INFO
    END
    Close PowerPoint Presentation

Verify Phase Events Present
    [Documentation]    Verify that phase events are represented on the timeline
    [Tags]    powerpoint    structural    phases
    # Get phases from Excel
    ${all_events}=    Load Excel And Get Expected Events    ${EXCEL_FILE_PATH}    ${EXCEL_SHEET_NAME}
    ${phases}=    Create List
    FOR    ${event}    IN    @{all_events}
        ${type}=    Get From Dictionary    ${event}    Type
        IF    "${type}" in ["Phase", "phase"]
            Append To List    ${phases}    ${event}
        END
    END
    
    ${phase_count}=    Get Length    ${phases}
    Skip If    ${phase_count} == 0    No phases in Excel data
    
    # Validate phases in PowerPoint
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    FOR    ${phase}    IN    @{phases}
        ${name}=    Get From Dictionary    ${phase}    Task Name
        ${shapes}=    Find Shapes By Text    ${name}
        ${found}=    Get Length    ${shapes}
        Log    Phase "${name}": ${found} shapes found    level=INFO
    END
    Close PowerPoint Presentation

Verify Feature Events Present
    [Documentation]    Verify that feature events are represented on the timeline
    [Tags]    powerpoint    structural    features
    # Get features from Excel
    ${all_events}=    Load Excel And Get Expected Events    ${EXCEL_FILE_PATH}    ${EXCEL_SHEET_NAME}
    ${features}=    Create List
    FOR    ${event}    IN    @{all_events}
        ${type}=    Get From Dictionary    ${event}    Type
        IF    "${type}" in ["Feature", "feature"]
            Append To List    ${features}    ${event}
        END
    END
    
    ${feature_count}=    Get Length    ${features}
    Skip If    ${feature_count} == 0    No features in Excel data
    
    # Validate features in PowerPoint
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    FOR    ${feature}    IN    @{features}
        ${name}=    Get From Dictionary    ${feature}    Task Name
        ${shapes}=    Find Shapes By Text    ${name}
        ${found}=    Get Length    ${shapes}
        Log    Feature "${name}": ${found} shapes found    level=INFO
    END
    Close PowerPoint Presentation

Verify Shape Positions Are Valid
    [Documentation]    Verify that shapes are positioned within slide bounds
    [Tags]    powerpoint    structural    positions
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${dimensions}=    Get Slide Dimensions
    ${shapes}=    Get Shapes On Slide    0
    
    FOR    ${shape}    IN    @{shapes}
        ${left}=    Get From Dictionary    ${shape}    left
        ${top}=    Get From Dictionary    ${shape}    top
        ${width}=    Get From Dictionary    ${shape}    width
        ${height}=    Get From Dictionary    ${shape}    height
        
        # Check shape is within bounds (with tolerance)
        Should Be True    ${left} >= -50    Shape ${shape}[name] left position out of bounds: ${left}
        Should Be True    ${top} >= -50    Shape ${shape}[name] top position out of bounds: ${top}
        Should Be True    ${left} + ${width} <= ${dimensions}[width] + 100    Shape ${shape}[name] extends beyond right edge
    END
    Close PowerPoint Presentation

Verify Presentation Summary
    [Documentation]    Generate and log a complete presentation summary
    [Tags]    powerpoint    reporting
    Load PowerPoint Presentation    ${PPTX_FILE_PATH}
    ${summary}=    Get Presentation Summary
    
    Log    File: ${summary}[file_path]    level=INFO
    Log    Slides: ${summary}[slide_count]    level=INFO
    Log    Dimensions: ${summary}[dimensions]    level=INFO
    
    FOR    ${slide}    IN    @{summary}[slides]
        Log    Slide ${slide}[index]: ${slide}[shape_count] shapes, ${slide}[text_shapes] with text    level=INFO
    END
    
    Close PowerPoint Presentation

*** Keywords ***
Setup PowerPoint Test Suite
    [Documentation]    Setup for PowerPoint test suite
    Log    PowerPoint validation test suite starting    level=INFO
    ${pptx_exists}=    Run Keyword And Return Status    File Should Exist    ${PPTX_FILE_PATH}
    IF    not ${pptx_exists}
        Log    WARNING: PowerPoint file not found at ${PPTX_FILE_PATH}    level=WARN
        Log    Please generate a timeline using the VBA macro first    level=WARN
    END

Cleanup PowerPoint Test Suite
    [Documentation]    Cleanup for PowerPoint test suite
    Log    PowerPoint validation test suite completed    level=INFO

