"""
PowerPoint Validator Library for Robot Framework
Validates PowerPoint presentations generated by the VBA timeline generator.
Uses python-pptx for structural validation without requiring PowerPoint installed.
"""
import os
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.dml.color import RGBColor


class PowerPointValidator:
    """Validates PowerPoint presentations for timeline structure and content."""

    def __init__(self):
        self.presentation = None
        self.file_path = None
        
        # Expected timeline configuration (matches VBA globalConfig)
        self.expected_config = {
            "slide_width": 960,  # Points (16:9 aspect ratio)
            "slide_height": 540,
            "timeline_axis_y": 110,
            "swimlane_header_width": 100,
            "lane_height": 48,
        }
        
        # Color mapping (RGB values from VBA GetColor function)
        self.color_map = {
            "red": RGBColor(192, 80, 77),
            "blue": RGBColor(79, 129, 189),
            "green": RGBColor(155, 187, 89),
            "orange": RGBColor(247, 150, 70),
            "purple": RGBColor(128, 100, 162),
            "yellow": RGBColor(255, 192, 0),
            "gray": RGBColor(128, 128, 128),
            "grey": RGBColor(128, 128, 128),
        }

    def load_presentation(self, file_path: str) -> bool:
        """
        Load a PowerPoint presentation for validation.

        Args:
            file_path: Path to the .pptx file

        Returns:
            True if loaded successfully, False otherwise
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"PowerPoint file not found: {file_path}")

        try:
            self.presentation = Presentation(file_path)
            self.file_path = file_path
            return True
        except Exception as e:
            raise RuntimeError(f"Error loading PowerPoint file: {str(e)}")

    def close_presentation(self):
        """Close the current presentation."""
        self.presentation = None
        self.file_path = None

    def get_slide_count(self) -> int:
        """Get the number of slides in the presentation."""
        if not self.presentation:
            raise RuntimeError("No presentation loaded")
        return len(self.presentation.slides)

    def get_slide_dimensions(self) -> Dict[str, float]:
        """
        Get slide dimensions in points.

        Returns:
            Dictionary with width and height in points
        """
        if not self.presentation:
            raise RuntimeError("No presentation loaded")

        # Convert EMUs to points (914400 EMUs per inch, 72 points per inch)
        width_pts = self.presentation.slide_width / 914400 * 72
        height_pts = self.presentation.slide_height / 914400 * 72

        return {
            "width": round(width_pts, 2),
            "height": round(height_pts, 2),
            "aspect_ratio": round(width_pts / height_pts, 2)
        }

    def get_shapes_on_slide(self, slide_index: int = 0) -> List[Dict[str, Any]]:
        """
        Get all shapes on a slide with their properties.

        Args:
            slide_index: Index of the slide (0-based)

        Returns:
            List of dictionaries with shape properties
        """
        if not self.presentation:
            raise RuntimeError("No presentation loaded")

        slide_index = int(slide_index)  # Ensure integer
        if slide_index >= len(self.presentation.slides):
            raise IndexError(f"Slide index {slide_index} out of range")

        slide = self.presentation.slides[slide_index]
        shapes = []

        for shape in slide.shapes:
            shape_info = {
                "name": shape.name,
                "shape_type": str(shape.shape_type),
                "left": round(shape.left / 914400 * 72, 2),  # Convert to points
                "top": round(shape.top / 914400 * 72, 2),
                "width": round(shape.width / 914400 * 72, 2),
                "height": round(shape.height / 914400 * 72, 2),
                "has_text": shape.has_text_frame,
            }

            # Get text content if available
            if shape.has_text_frame:
                text_content = []
                for paragraph in shape.text_frame.paragraphs:
                    for run in paragraph.runs:
                        text_content.append(run.text)
                shape_info["text"] = " ".join(text_content).strip()

            # Get fill color if available
            try:
                if shape.fill.type is not None:
                    if hasattr(shape.fill, 'fore_color') and shape.fill.fore_color:
                        if hasattr(shape.fill.fore_color, 'rgb'):
                            shape_info["fill_color"] = str(shape.fill.fore_color.rgb)
            except Exception:
                pass

            shapes.append(shape_info)

        return shapes

    def find_shapes_by_text(
        self,
        search_text: str,
        slide_index: int = 0,
        partial_match: bool = True
    ) -> List[Dict[str, Any]]:
        """
        Find shapes containing specific text.

        Args:
            search_text: Text to search for
            slide_index: Index of the slide
            partial_match: If True, matches partial text

        Returns:
            List of matching shapes
        """
        slide_index = int(slide_index)  # Ensure integer
        shapes = self.get_shapes_on_slide(slide_index)
        matches = []

        for shape in shapes:
            if "text" in shape:
                if partial_match:
                    if search_text.lower() in shape["text"].lower():
                        matches.append(shape)
                else:
                    if search_text.lower() == shape["text"].lower():
                        matches.append(shape)

        return matches

    def find_shapes_by_position(
        self,
        y_position: float,
        tolerance: float = 10.0,
        slide_index: int = 0
    ) -> List[Dict[str, Any]]:
        """
        Find shapes at a specific Y position.

        Args:
            y_position: Y position in points
            tolerance: Tolerance in points
            slide_index: Index of the slide

        Returns:
            List of shapes at the specified position
        """
        slide_index = int(slide_index)  # Ensure integer
        y_position = float(y_position)  # Ensure float
        tolerance = float(tolerance)  # Ensure float
        shapes = self.get_shapes_on_slide(slide_index)
        matches = []

        for shape in shapes:
            if abs(shape["top"] - y_position) <= tolerance:
                matches.append(shape)

        return matches

    def validate_timeline_structure(self, slide_index: int = 0) -> Dict[str, Any]:
        """
        Validate the overall timeline structure on a slide.

        Args:
            slide_index: Index of the slide to validate

        Returns:
            Dictionary with validation results
        """
        if not self.presentation:
            raise RuntimeError("No presentation loaded")
        
        slide_index = int(slide_index)  # Ensure integer

        results = {
            "valid": True,
            "errors": [],
            "warnings": [],
            "details": {}
        }

        shapes = self.get_shapes_on_slide(slide_index)
        results["details"]["total_shapes"] = len(shapes)

        # Check for timeline axis (horizontal line near expected Y position)
        axis_shapes = self.find_shapes_by_position(
            self.expected_config["timeline_axis_y"],
            tolerance=20.0,
            slide_index=slide_index
        )
        results["details"]["axis_shapes_found"] = len(axis_shapes)

        if len(axis_shapes) == 0:
            results["warnings"].append("Timeline axis not found at expected position")

        # Check for text shapes (labels, headers)
        text_shapes = [s for s in shapes if s.get("text")]
        results["details"]["text_shapes"] = len(text_shapes)

        # Check for swimlane headers (typically on the left side)
        header_candidates = [
            s for s in text_shapes 
            if s["left"] < self.expected_config["swimlane_header_width"]
        ]
        results["details"]["swimlane_headers"] = len(header_candidates)

        return results

    def validate_swimlanes(
        self,
        expected_swimlanes: List[str],
        slide_index: int = -1
    ) -> Dict[str, Any]:
        """
        Validate that expected swimlanes are present.

        Args:
            expected_swimlanes: List of expected swimlane names
            slide_index: Index of the slide (-1 to check all slides)

        Returns:
            Dictionary with validation results
        """
        results = {
            "valid": True,
            "found": [],
            "missing": [],
            "extra": []
        }

        # Collect text from specified slide or all slides
        found_text = set()
        if slide_index == -1:
            # Check all slides
            for idx in range(len(self.presentation.slides)):
                shapes = self.get_shapes_on_slide(idx)
                for shape in shapes:
                    if "text" in shape and shape["text"]:
                        found_text.add(shape["text"].strip())
        else:
            slide_index = int(slide_index)
            shapes = self.get_shapes_on_slide(slide_index)
            for shape in shapes:
                if "text" in shape and shape["text"]:
                    found_text.add(shape["text"].strip())

        # Check for expected swimlanes
        for swimlane in expected_swimlanes:
            found = False
            for text in found_text:
                if swimlane.lower() in text.lower():
                    results["found"].append(swimlane)
                    found = True
                    break
            if not found:
                results["missing"].append(swimlane)
                results["valid"] = False

        return results

    def validate_events(
        self,
        expected_events: List[Dict[str, str]],
        slide_index: int = -1
    ) -> Dict[str, Any]:
        """
        Validate that expected events are present.

        Args:
            expected_events: List of dictionaries with event details
            slide_index: Index of the slide (-1 to check all slides)

        Returns:
            Dictionary with validation results
        """
        results = {
            "valid": True,
            "found": [],
            "missing": [],
            "details": []
        }

        # Determine which slides to check
        if slide_index == -1:
            slide_indices = range(len(self.presentation.slides))
        else:
            slide_indices = [int(slide_index)]

        for event in expected_events:
            task_name = event.get("Task Name", "")
            if not task_name:
                continue

            # Search for shape with event name across specified slides
            found = False
            for idx in slide_indices:
                matching = self.find_shapes_by_text(task_name, idx, partial_match=True)
                if matching:
                    results["found"].append(task_name)
                    results["details"].append({
                        "event": task_name,
                        "slide": idx,
                        "shapes_found": len(matching),
                        "positions": [(s["left"], s["top"]) for s in matching]
                    })
                    found = True
                    break
            
            if not found:
                results["missing"].append(task_name)
                results["valid"] = False

        return results

    def get_shape_colors(self, slide_index: int = 0) -> List[Dict[str, Any]]:
        """
        Get all shapes with their fill colors.

        Args:
            slide_index: Index of the slide

        Returns:
            List of shapes with color information
        """
        slide_index = int(slide_index)  # Ensure integer
        shapes = self.get_shapes_on_slide(slide_index)
        colored_shapes = []

        for shape in shapes:
            if "fill_color" in shape:
                colored_shapes.append({
                    "name": shape["name"],
                    "text": shape.get("text", ""),
                    "color": shape["fill_color"],
                    "position": (shape["left"], shape["top"])
                })

        return colored_shapes

    def get_presentation_summary(self) -> Dict[str, Any]:
        """
        Get a summary of the presentation structure.

        Returns:
            Dictionary with presentation summary
        """
        if not self.presentation:
            raise RuntimeError("No presentation loaded")

        summary = {
            "file_path": self.file_path,
            "slide_count": len(self.presentation.slides),
            "dimensions": self.get_slide_dimensions(),
            "slides": []
        }

        for i, slide in enumerate(self.presentation.slides):
            shapes = self.get_shapes_on_slide(i)
            slide_info = {
                "index": i,
                "shape_count": len(shapes),
                "text_shapes": len([s for s in shapes if s.get("text")]),
                "colored_shapes": len([s for s in shapes if s.get("fill_color")])
            }
            summary["slides"].append(slide_info)

        return summary

    def compare_with_baseline(
        self,
        baseline_path: str,
        slide_index: int = 0
    ) -> Dict[str, Any]:
        """
        Compare current presentation with a baseline.

        Args:
            baseline_path: Path to baseline .pptx file
            slide_index: Index of the slide to compare

        Returns:
            Dictionary with comparison results
        """
        slide_index = int(slide_index)  # Ensure integer
        
        # Load baseline
        baseline = Presentation(baseline_path)
        
        if slide_index >= len(baseline.slides):
            raise IndexError(f"Baseline doesn't have slide {slide_index}")

        results = {
            "match": True,
            "differences": [],
            "current_shapes": 0,
            "baseline_shapes": 0
        }

        # Get shapes from both
        current_shapes = self.get_shapes_on_slide(slide_index)
        
        # Temporarily switch to baseline
        original_pres = self.presentation
        self.presentation = baseline
        baseline_shapes = self.get_shapes_on_slide(slide_index)
        self.presentation = original_pres

        results["current_shapes"] = len(current_shapes)
        results["baseline_shapes"] = len(baseline_shapes)

        # Compare shape counts
        if len(current_shapes) != len(baseline_shapes):
            results["match"] = False
            results["differences"].append(
                f"Shape count differs: {len(current_shapes)} vs {len(baseline_shapes)}"
            )

        # Compare text content
        current_text = set(s.get("text", "") for s in current_shapes if s.get("text"))
        baseline_text = set(s.get("text", "") for s in baseline_shapes if s.get("text"))

        missing_text = baseline_text - current_text
        extra_text = current_text - baseline_text

        if missing_text:
            results["match"] = False
            results["differences"].append(f"Missing text: {missing_text}")

        if extra_text:
            results["match"] = False
            results["differences"].append(f"Extra text: {extra_text}")

        return results

    def export_slide_to_image(
        self,
        slide_index: int = 0,
        output_path: str = None
    ) -> str:
        """
        Export a slide to an image (requires PowerPoint on Windows).
        Falls back to creating a placeholder if PowerPoint is not available.

        Args:
            slide_index: Index of the slide
            output_path: Output path for the image

        Returns:
            Path to the exported image
        """
        if output_path is None:
            output_path = f"slide_{slide_index}.png"

        # Try to use COM automation on Windows
        try:
            import platform
            if platform.system() == "Windows":
                return self._export_with_com(slide_index, output_path)
        except ImportError:
            pass

        # Fallback: Create a summary text file instead
        summary_path = output_path.replace(".png", "_summary.txt")
        shapes = self.get_shapes_on_slide(slide_index)
        
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(f"Slide {slide_index} Summary\n")
            f.write("=" * 40 + "\n")
            f.write(f"Total shapes: {len(shapes)}\n\n")
            for shape in shapes:
                f.write(f"Shape: {shape['name']}\n")
                f.write(f"  Position: ({shape['left']}, {shape['top']})\n")
                f.write(f"  Size: {shape['width']} x {shape['height']}\n")
                if shape.get("text"):
                    f.write(f"  Text: {shape['text']}\n")
                f.write("\n")

        return summary_path

    def _export_with_com(self, slide_index: int, output_path: str) -> str:
        """Export slide using PowerPoint COM automation (Windows only)."""
        import win32com.client
        
        ppt_app = win32com.client.Dispatch("PowerPoint.Application")
        ppt_app.Visible = True
        
        try:
            presentation = ppt_app.Presentations.Open(
                os.path.abspath(self.file_path),
                ReadOnly=True
            )
            
            slide = presentation.Slides(slide_index + 1)  # 1-based index
            slide.Export(os.path.abspath(output_path), "PNG")
            
            presentation.Close()
            return output_path
        finally:
            ppt_app.Quit()

